mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('result/<int:id>', views.result),
    path('qna', views.qna, name='qna'),
    path('add_question', views.add_question),
    # qna/add_question  or  ../add_question
    path('<int:number>/data/<str:email>', views.data),

    path('data', views.data),
    path('', views.index),
    path('<int:id>', views.detail, name='detail'),
    path('vote/', views.vote, name='vote'),
]


# index.html의 디테일과 연결



# views 에 인덱스 먼저 해결 후

polls/models.py
from django.db import models

from django.db import models

# Ctrl + Alt + l = 정렬

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text              #override - 터미널에서 print() 하면 내용이 직접 출력됨

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text + ' // ' + str(self.votes)

# Question 과 Choice 외래키로 연결되어 있음

polls/views.py
from django.http import HttpResponse
from django.shortcuts import render

from polls.models import Question, Choice
from django.utils import timezone 


def qna(request):
    return render(request, 'polls/qna.html', {})

def add_question(request):
    text = request.POST['text']

    q = Question(
        question_text=text,
        pub_date=timezone.now())
    q.save()
    return HttpResponse('접수되었습니다')

# def add_question(request):
#     text = request.POST['text']
#
#     q = Question(
#         question_text=text,
#         pub_date=timezone.now())
#     q.save()
#     return  HttpResponse('입력 완료')

def data(request, email, number):
    # http: // localhost: 8000 / polls / data?user_name = kim
    value = request.GET['user_name']
    return HttpResponse(value + email + str(number))

def vote(request):
    choice = request.POST['choice']
    c = Choice.objects.get(pk=choice)
    c.votes = c.votes + 1
    c.save()
    print('@@@@@@@@', choice)
    # 정상적으로 작동하면 cmd 서버에 @@@@@@@@@ on
    return render(request, 'polls/vote.html', {})

def detail(request, id):
    question = Question.objects.get(id=id)
    return render(request, 'polls/detail.html', {'item': question})

def index(request):
    list = Question.objects.all()

    # return render(request, ''. {})
    return render(request, 'polls/index.html', {'question': list})

def result(request, id):
    question = Question.objects.get(pk=id)
    return render(request, 'polls/result.html', {'question' : question})

polls/templates/polls/detail.html
{{ item.question_text }}<br>
{{ item.pub_date }}<br>

{{ item.choice_set.all }}
<!--{% for c in item.choice_set.all %}-->
    <!--<input type="radio">-->
    <!--{{ c.choice_text}}-->
<!--{% endfor %}-->


<form action = "vote/" method = "post">
   {% for c in item.choice_set.all %}
    <input type="radio" name="choice" value="{{ c.id }}">{{ c.choice_text }}
{% endfor %}
    {% csrf_token %}    <!-- 보안 조치-->
    <input type="submit" value="투표">
</form>

polls/templates/polls/index.html
<ul>
{% for q in question %}
    <li>
        <!--<a href="{{ q.id }}">     &lt;!&ndash; 상대경로 === 현재경로 + 입력된 경로  polls에서 클릭하면 polls/1/detail로 이동 &ndash;&gt;-->
        <a href="{% url 'detail' q.id %}">
        {{ q.question_text }}
    <!--#question_text from models.pyu-->
        </a>
    </li>
{% endfor %}
</ul>



<!--url.py의 detail과 연결-->

polls/templates/polls/qna.html
'질문 받는다'

<!--<form action = "polls/" method = "post">-->
   <!--{% for c in item.choice_set.all %}-->
    <!--<input type="submit" name="text" value="제출">{{ c.choice_text }}-->
<!--{% endfor %}-->
    <!--{% csrf_token %}    &lt;!&ndash; 보안 조치&ndash;&gt;-->
    <!--<input type="submit" value="제출">-->
<!--</form>-->

<br><br><br><br>

<!--상대경로-->
<form action="add_question" method="post">
                <!--../question-->
    질문: <input type="text" name="text">
    <br><br><br>
    {% csrf_token %}
    <input type="submit">
</form>

polls/templates/polls/result.html
질문 : {{ question.question_text }}


<br>
{% for choice in question.choice_set.all %}
    {{ choice.choice_text }} --> {{ choice.votes }}<br>

{% endfor %}

polls/templates/polls/vote.html
투표 완료